version: '3.7'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/var/www/html:cached #volumeで手元のディレクトリのコードをコンテナ内に反映してくれる
